import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/website/Navbar";
import Footer from "@/components/website/Footer";

// const inter = Inter({ subsets: ["latin"] });

const josefin = Josefin_Sans({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Ghoriwala Mart",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={josefin.className}>
        {/* navbar  */}
        <Navbar />
        <div className="">{children}</div>
        {/* footer  */}
        <Footer />
      </body>
    </html>
  );
}
